title: yosaka's note
description: 備忘録
author: "yosakax"

theme: minima

base_url: /gh-pages-minima-starter

# Minima social links
twitter_username: asmkana
github_username: yosakax
# rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

timezone:
  - "Asia/Tokyo"

exclude:
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
